CREATE DATABASE CRUD_PHP_PDO;
USE CRUD_PHP_PDO;

CREATE TABLE Paciente(
    ID INT AUTO_INCREMENT,
    Nome VARCHAR(100),
    Email VARCHAR(60) NOT NULL UNIQUE,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    Telefone VARCHAR(15) NOT NULL,
    DataDeNascimento DATE,
    Sexo ENUM('Masculino', 'Feminino', 'Outro'),
    Endereço VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Estado VARCHAR(2) NOT NULL,
    CEP VARCHAR(7) NOT NULL,
    MotivoDaConsulta VARCHAR(250) NOT NULL,
    DataCadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
)
ENGINE = InnoDB;

CREATE TABLE Recepcionista(
    ID INT AUTO_INCREMENT,
    Codigo INT UNIQUE NOT NULL,
    Nome VARCHAR(240) NOT NULL,
    Senha VARCHAR(60) NOT NULL,
    PRIMARY KEY(ID)
)
ENGINE = InnoDB;

CREATE TABLE Medico(
    ID INT AUTO_INCREMENT,
    Matricula INT UNIQUE NOT NULL,
    Nome VARCHAR(240) NOT NULL,
    Senha VARCHAR(60) NOT NULL,
    PRIMARY KEY(ID)
)
